use anyhow::Result;
use clap::{Args, Parser, Subcommand};
use durandal_core::CliCommand;
use durandal_derives::CliDispatch;

#[derive(Parser)]
#[clap(name = "cli-dispatch-test")]
pub struct Cli {
    #[clap(subcommand)]
    pub command: Commands,
}

impl Cli {
    pub fn run() -> Result<()> {
        // We expect the dispatch to run be generated by the CliDispatch derive
        Self::parse().command.run()
    }
}

#[derive(Subcommand, CliDispatch)]
pub enum Commands {
    Foo(Foo),
    Bar(Foo),
    // I'd like to test this, but it relies on a crate name. Particularly the
    // crate_name! macro from clap. So I guess we have to figure that out.
    // #[clap(external_subcommand)]
    // External(Vec<String>),
}

#[derive(Args)]
pub struct Foo {}

impl CliCommand for Foo {
    fn run(&self) -> anyhow::Result<()> {
        Ok(())
    }
}

fn main() {}
